version: '3.8'
services:
  mysql-db:
    # Nombre de contenedor MYSQL
    image: mysql:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mstgo
    ports:
      - 3307:3306
  app:
    container_name: app-lab1_mingeso
    image: rezzzie/lab1_mingeso
    ports:
      - '8090:8090'
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/mstgo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=mysql
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
